---
- name: install php packages
  with_items: "{{ php_packages }}"
  pkgng:
    name: "{{ item.name }}"
  notify:
    - restart php-fpm

- name: configure php-fpm pool
  template:
    src: www.conf.j2
    dest: /usr/local/etc/php-fpm.d/www.conf
  notify:
    - restart php-fpm

- name: enable php-fpm
  template:
    src: php_fpm.j2
    dest: /etc/rc.conf.d/php_fpm
  notify:
    - restart php-fpm
